//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalles_Fact_Reparaciones
    {
        public int id_det_fact { get; set; }
        public int id_factura { get; set; }
        public string nombre_producto { get; set; }
        public int id_categoria_producto { get; set; }
        public string descripcion_producto { get; set; }
        public string descripcion_problema { get; set; }
        public decimal valor_reparacion { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public System.DateTime fecha_entrega { get; set; }
        public int id_estado { get; set; }
    
        public virtual Categoria_Producto Categoria_Producto { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Factura Factura { get; set; }
    }
}
