//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.Detalles_Fact_Alquiler = new HashSet<Detalles_Fact_Alquiler>();
            this.Detalles_Fact_Compras = new HashSet<Detalles_Fact_Compras>();
            this.Detalles_Fact_Reparaciones = new HashSet<Detalles_Fact_Reparaciones>();
            this.Envios = new HashSet<Envio>();
            this.Trans_Tarjeta = new HashSet<Trans_Tarjeta>();
        }
    
        public int id_factura { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public int id_metpago { get; set; }
        public int id_empleado { get; set; }
        public decimal subtotal_servicio { get; set; }
        public int id_tipo_compra { get; set; }
        public decimal impuestos { get; set; }
        public decimal total_descuento { get; set; }
        public decimal monto_total { get; set; }
        public string ncf { get; set; }
        public System.DateTime vencimiento_fact { get; set; }
        public string nombre_cliente { get; set; }
        public int id_cliente { get; set; }
        public bool entrega_domicilio { get; set; }
        public int id_sucursal { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_Fact_Alquiler> Detalles_Fact_Alquiler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_Fact_Compras> Detalles_Fact_Compras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_Fact_Reparaciones> Detalles_Fact_Reparaciones { get; set; }
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Envio> Envios { get; set; }
        public virtual Met_Pago Met_Pago { get; set; }
        public virtual Sucursale Sucursale { get; set; }
        public virtual Tipo_Compra Tipo_Compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trans_Tarjeta> Trans_Tarjeta { get; set; }
    }
}
