//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico_Productos
    {
        public int id_producto { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_cambio { get; set; }
        public bool activo { get; set; }
        public decimal precio { get; set; }
        public string descripcion { get; set; }
        public int id_categoria { get; set; }
    
        public virtual Categoria_Producto Categoria_Producto { get; set; }
    }
}
