//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info_Registro_Empleados
    {
        public int id_registro { get; set; }
        public int id_empleado { get; set; }
        public string hash_password { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public bool activo { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
