//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Compra_Producto = new HashSet<Compra_Producto>();
            this.Detalles_Fact_Alquiler = new HashSet<Detalles_Fact_Alquiler>();
            this.Detalles_Fact_Compras = new HashSet<Detalles_Fact_Compras>();
            this.Fotos_Productos = new HashSet<Fotos_Productos>();
            this.Inventarios = new HashSet<Inventario>();
        }
    
        public int id_producto { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public bool activo { get; set; }
        public decimal precio { get; set; }
        public string descripcion { get; set; }
        public int id_categoria { get; set; }
    
        public virtual Categoria_Producto Categoria_Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra_Producto> Compra_Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_Fact_Alquiler> Detalles_Fact_Alquiler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_Fact_Compras> Detalles_Fact_Compras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fotos_Productos> Fotos_Productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventarios { get; set; }
    }
}
