//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trans_Tarjeta
    {
        public int id_trans { get; set; }
        public int id_factuta { get; set; }
        public int id_tarjeta { get; set; }
        public System.DateTime fecha_registro { get; set; }
    
        public virtual Factura Factura { get; set; }
    }
}
